# By Srija Belide
# Donut Art
# this code generates donuts using for loops, classes, and multiple patterns 
# imports needed libraries for this code
import simplegui
import math
import random

# global constants
WIDTH = 800
HEIGHT = 600
SIN = math.sin
COS = math.cos
RADIANS = math.radians(360)

# lists declaration
donuts = [] # used to hold donuts  
clouds = []  # used to hold the clouds created
patterned_lines = []   # used to hold the lines making up the surface texture
sprinkles = []    # used to hold the arcs creating sprinkles
rainbows = []  # used to hold the arcs creating rainbows
sun = [] # used to hold the sun created

# Helper functions
# Function to generate random hexcolor
def random_colour():
    global colour
    # indexing helps get rid of the '0x'
    r = hex(random.randint(100, 200))[2:]
    g = hex(random.randint(100, 200))[2:]
    b = hex(random.randint(100, 300))[2:]
    colour = "#"+r+g+b
    return colour
        
# Function that generates donuts making up the base of the donut
def generate_donuts(x_offset, y_offset, colour): 
    
    for i in range(60):
        center = (x_offset + 300+120*math.cos(i) ,y_offset + 300+120*math.sin(i)) # trig is used to generate a circular pattern of the donuts
        radius = 40  # defines the size of the donuts
        line_width = 4+i # creates a layered effect through increments
        new_donut = Circle(center, radius, line_width, colour) # a random colour is assigned to the first donut
        donuts.append(new_donut) 
            
# Function that has 2 sets of for loops to generate sprinkles in 2 different directions
def generate_sprinkles(x_offset, y_offset):
    global line_width
    # first set of sprinkles
    for a in range(30): # to generate 30 sprinkles
        for i in range(4): # to add variations to the sprinkles
            # randomizing sprinkles displacement
            r = random.randint(110, 130)
            t = random.randint(10, 40)
            line_colour = random_colour() # Random color for each sprinkle
            center = [x_offset + 300+r*COS(a) +t*(COS(i)),
                      y_offset + 290+r*SIN(a) + t*(SIN(i))]
            radius = 15 
            start_angle = -1
            line_width = 1.5 
            end_angle = 0  
            set1_sprinkles = Arcs(center, radius, start_angle, end_angle, line_width, line_colour)
            sprinkles.append(set1_sprinkles) # adds sprinkles to the list of sprinkles
           
    # second loop to create the next set of sprinkles in opposite direction
    for a in range(20): # to generate 20 sprinkles
        for i in range(4): # to add variations to the sprinkles
            # random displacement of sprinkles
            r = random.randint(100, 119)
            t = random.randint(20, 50)
            line_colour = random_colour() # random colour for each sprinkle
            center = [x_offset + 290+r*COS(a) +t*(COS(i)),
                      y_offset + 290+r*SIN(a) + t*(SIN(i))]
            radius = 15
            start_angle = 0
            end_angle = 1
            set2_sprinkles = Arcs(center, radius, start_angle, end_angle, line_width, line_colour)
            # to add the second set of sprinkles
            sprinkles.append(set2_sprinkles)
           
 # Function of nested patterned lines to create a textured wooden ground
def lines():
    for l in range(15):
        
        # l is multiplied by 30 to space the Y axis equally for each iteration
        point1 = (0, 400+(l*30)) 
        point2 = (800, 350+(l*30))
        line_width = 0.5+l
        colour = "#33210d" 
        outer_line = Line(point1, point2, line_width, colour)
        patterned_lines.append(outer_line)
        
        for i in range(3):
            offset = (i+5) * 10
            point1_inner = (0, 400+(l*30) + offset)
            point2_inner = (800, 350+(l*30) + offset)
            inner_line_width = 0.7
            inner_colour = "#a76b2c" 
            inner_line = Line(point1_inner, point2_inner, inner_line_width, inner_colour)
            patterned_lines.append(inner_line)
                
# Function to generate rainbows
def rainbow():
    for r in range(7):
        center = (100 + (20*r), 100 + (15*r))
        radius = 120 + (20*r)
        start_angle = 3
        end_angle = -1
        line_width = 6
        rainbow = ["red", "orange", "yellow", "green", "blue", "indigo", "purple"] 
        # the colors are generated by modding the list of rainbow colors
        new_rainbow = Arcs(center, radius, start_angle, end_angle, line_width, rainbow[r%7])
        rainbows.append(new_rainbow)
            
# Function to create a irregular cloud
def generate_clouds(x,y): 
    for g in range(15):
        # generates randomized circles making up a cloud
        x_offset = random.randint(-50, 50)
        y_offset = random.randint(-10, 10)
        radius = random.randint(30, 40+g)  
        color = "white"  
        clouds.append(Circle([x + x_offset, y + y_offset], radius, 1, color, color))

# Function to generate a sun
def generate_sun():
    for r in range(16):
        # creates the circular line patterns of a sun
        angle = RADIANS/16 * r  
        start_pos = (800+r*COS(angle), 30+r*SIN(angle))
        end_pos = (800+(r + 60)*COS(angle), 30+(r + 60)*SIN(angle))
        rays = Line(start_pos, end_pos, 2, "yellow")
        sun.append(rays)
        
    # creates the yellow base of a sun   
    center = (800,30) 
    radius = 40  
    line_width = 4 
    new_sun = Circle(center, radius, line_width, "yellow", "yellow")
    sun.append(new_sun)
            
#Classes
# template for creating circles
class Circle:
    def __init__(self, center, radius, line_width, line_colour, fill_color=None):
        self.center = center
        self.rad = radius
        self.width = line_width
        self.colour = line_colour
        self.fill = fill_color
        
    def draw(self,canvas):
        canvas.draw_circle(self.center, self.rad, self.width, self.colour, self.fill)

# template for creating lines        
class Line:
    def __init__(self, point1, point2, line_width, line_colour):
        self.p1 = point1
        self.p2 = point2
        self.width = line_width
        self.colour = line_colour
        
    def draw(self,canvas):
        canvas.draw_line(self.p1, self.p2, self.width, self.colour)

# template for creating Arcs        
class Arcs:
    def __init__(self, center, radius, start_angle, end_angle, line_width, line_color):
        self.center = center
        self.rad = radius
        self.strt_ang = start_angle
        self.end_ang = end_angle
        self.width = line_width
        self.colour = line_color
        
    def draw(self, canvas):
        canvas.draw_arc(self.center, self.rad, self.strt_ang, self.end_ang, self.width, self.colour)
    
# generates 3 different donuts 
for d in range(3): 
    # x and y offsets specify the spacing between each donut
    x_offset = 5 + (2*160) * (d-1)
    y_offset = 20* d
    donut_colour = ["#ff69b4", "#add8e6"]
    # a list is used to generate  different colours for the last 2 donuts
    generate_donuts(x_offset, y_offset, donut_colour[d%2])
    
# to replicate the sprinkles pattern in all 3 donuts
for s in range(3):
    # to specify the spacing between each sprinkle pattern
    x_offset = 5 + (2*160) * (s-1) 
    y_offset = 20 * s
    generate_sprinkles(x_offset, y_offset)
    
# generates 3 clouds
first_cloud = generate_clouds(200, 50)
second_cloud = generate_clouds(500, 60)
third_cloud = generate_clouds(700, 50)

# Handlers
# Button Handlers
# to increase the size of the sprinkles 
def inc_sprinkles_handler():
    for sprinkle in sprinkles:
        sprinkle.width += 1
        if sprinkle.width > 5: # size limit of 5
            sprinkle.width = 5 
            
# to decrease the size of the sprinkles
def dec_sprinkles_handler():
    for sprinkle in sprinkles:
        sprinkle.width -= 1
        if sprinkle.width < 1: # minimum size of 1
            sprinkle.width = 1
            
  # to increase the size of the donuts
def inc_donuts_handler():
    for l in donuts:
        l.rad += 3
        if l.rad > 50: # size limit of 50
            l.rad = 50
            
# to decrease the size of the donuts
def dec_donuts_handler():           
    for x in donuts:
        x.rad -= 3 
        if x.rad < 30: # minimum size of 30
            x.rad = 30

# Handler to draw on canvas
def draw(canvas):
    canvas.draw_polygon([(0, 400), (800, 400), (800, 600), (0, 600)], 12, "#72491e", '#72491e') # draws the base of the wooden texture
    for line in patterned_lines: # draws the lines in the texture
        line.draw(canvas)
    for donut in donuts:         # draws the donuts
        donut.draw(canvas)
    for sprinkle in sprinkles:   # draws the sprinkles
        sprinkle.draw(canvas)
    for cloud in clouds:         # draws the clouds
        cloud.draw(canvas)
        # makes the clouds move
        cloud.center[0] += 1 # increments the cloud's x-coordinate by 1 
        if cloud.center[0] % WIDTH == 0:  # checks if the center has reached the edge 
            cloud.center[0] = 0 # resets the x-coordinate to 0 to make it reappear on the left side
            # randomized x and y to create different cloud shapes for each run
            cloud.center[1] = random.randint(50, 70)  
            cloud.center[0] = random.randint(50, 70)
    for rainbow in rainbows:     # draws the rainbows
        rainbow.draw(canvas)
    for s in sun:                # draws the sun
        s.draw(canvas)
        
# Frames            
# Creates a frame and assign callbacks to event handlers
frame = simplegui.create_frame("Circle Art", 800, 600)
frame.set_draw_handler(draw)

# sets a background color to the frame
frame.set_canvas_background("black")

# button to increase the size of the sprinkles
frame.add_button("increase sprinkles size", inc_sprinkles_handler)

# button to decrease the size of the sprinkles
frame.add_button("decrease sprinkles size", dec_sprinkles_handler)

# button to increase the size of the donuts
frame.add_button("increase donut size", inc_donuts_handler)

# button to decrease the size of the donuts
frame.add_button("decrease donut size", dec_donuts_handler)

# Start the frame animation
generate_donuts(x_offset, y_offset, random_colour())
generate_sprinkles(x_offset, y_offset)
rainbow()
lines()
generate_sun()
frame.start()