# -*- coding: utf-8 -*-
"""CS 11 final project_Srija Belide_Block B.ipynb

Original file is located at
    https://colab.research.google.com/drive/15oJuY4-6eRZmb9fAyvmbAslgP6C7Lj0w

# Main Objective:

This project simulates a spinner to model both experimental and theoretical probabilities visualized through various graph analyses. The project is split into 3 different parts, each part focusing on different aspects of these probabilities and a graphing representation.

##**Analysis:**

The following code models experimental vs theoretical probability of a spinner with equally sized sections numbered sequentially.

The theoretical probability calculates the favorable outcome of the spinner to land in each section. This is calculated by dividing each section by the total number of sections, which results in a constant probability across sections.

Experimental probability is generated by simulating random spins, where each section is selected randomly. This varies how many times each section is chosen by a spinner. The probability is then calculated by dividing the number of times the spinner lands on a specific section by the number of total spins.

The user can alter the number of sections and spins through a button with a maximum number of sections going up till 16.

## A bar graph analysis displaying both experimental and theoretical probabilities of each section in the spinner
"""

# By Srija Belide
# Part 1 of the project
'''This part models both experimental and theoretical probabilities
 of each section within a spinner.

 It provides a bar graph analysis of these probabilities allowing us to compare
 the differences. Users also have a scope to alternate the number of sections
  and spins in a spinner through a button.

 '''

# imports needed libraries for this simulation
import matplotlib.pyplot as plt
import random
import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output

# global variables
num_sec = 4 # initial sections of a spinner
num_spins = 5 # initial number of spins

# Helper functions
# function to generate both probabilities of each section
def spinner(num_sec, num_spins):
  ex_prob = [] # stores experimental probabilities
  spin_results = [] # stores the results of each spin

  # intializes the dictionary
  # sets section numbers as keys
  # sets number of times each section is generated as values
  section_counts = {i:0 for i in range(1, num_sec + 1)}

  # theoretical probability for each section
  t_prob = 1/num_sec

  # for loop to simulate spins and record results
  for i in range(num_spins):
    # randomly selects a spin outcome between the given sections
    spin = random.randint(1, num_sec)
    spin_results.append(spin)

# a nested for loop to update section counts based on the simulated spins
  for spin in spin_results:
    for i in range(1, num_sec + 1):
      if spin == i:
        section_counts[i] += 1 # updates the count for the selected section

# calculates experimental probability
# by dividing the counts for each section by the total number of spins
  for count in section_counts.values():
    calc_exprob = count/num_spins
    ex_prob.append(calc_exprob) # appends the experimental probabilities

  # returns both theoretical and experimental probabilities
  return t_prob, ex_prob


# function to plot the bar charts of the probabilities data
def plot_data(num_sec, num_spins):
  # unpacks the probabilities from the spinner function
  t_prob, ex_prob = spinner(num_sec, num_spins)
  # creates an array with the evenly spaced values of each section
  x = np.arange(1, (num_sec + 1))
  bar_total_width = 0.35 # total width of the 2 bars per section

  # plots the bar charts with the probabilities
  # the bar is positoned to the left of each section value
  plt.bar(x - bar_total_width/2, t_prob, width=0.3, label="Theoretical Probability")
  # the bar is positioned to the right of each section value
  plt.bar(x + bar_total_width/2, ex_prob, width=0.3, label="Experimental Probability")

  # labelling and arangement of the graph
  plt.xticks(np.arange(1, (num_sec + 1)))
  plt.xlabel("Sections")
  plt.ylabel("Probability")
  plt.title('Experimental vs Theoretical Probability of Sections in the Spinner')
  plt.legend()
  plt.show()


# calculates the differences between probabilities of each section
# checks if they are within the 0-5% variance
def check_error_bound():
  # unpacks the probabilities from the spinner function
  t_prob, ex_prob = spinner(num_sec, num_spins)
  # list comprehension to calculate the differences between probabilities
  differences = [x - t_prob for x in ex_prob]
  # maps the differences list to generate absolute values
  errors = list(map(abs, differences))

  # checks if all values satisfy the 0-5% variance range
  if all(0.00 <= error <= 0.05 for error in errors):
    # uses enumerate for section numbering
    for count, error in enumerate(errors, start=1):
      round_diff = round(error, ndigits=3) # rounds values to 3 decimal places
      print("Section", count, "has a variance of:", round_diff)
    print("Probabilities differences are within the 0-5% variance")
  else:
    print("Probabilities differences are not within the 0-5% variance")
    # resets the error list to ensure outdated values are not used
    errors = []
  print("The current number of spins are:", num_spins)
  return errors

# Button Handlers
# button to increase sections
inc_sections = widgets.Button(description="Increase Sections")
display(inc_sections)

# button to increase spins
inc_spins = widgets.Button(description="Increase Spins")
display(inc_spins)

# button to decrease spins
dec_spins = widgets.Button(description="Decrease Spins")
display(dec_spins)

# button to decrease sections
dec_sections = widgets.Button(description="Decrease Sections")
display(dec_sections)

# Button handler function to increase the sections in the spinner
def button_inc_sections(inc_sections):
  global num_sec
  num_sec += 1 # increases the sections by 1
  if num_sec >= 16: # section limit of 16
    num_sec = 16
  clear_output(wait=True) # clears the current plot
  # updates the plot with the new generated sections
  plot_data(num_sec, num_spins)
  check_error_bound() # checks if probabilities are within the variances
  # redisplays the 4 buttons
  display(inc_sections)
  display(inc_spins)
  display(dec_spins)
  display(dec_sections)


# Button handler function to increase the number of spins of a spinner
def button_inc_spins(inc_spins):
  global num_spins
  num_spins += 20 # spins increase by 20
  clear_output(wait=True) # clears the current plot
  # updates the plot with the new number of spins
  plot_data(num_sec, num_spins)
  check_error_bound() # checks if probabilities are within the variances
  # redisplays the 4 buttons
  display(inc_sections)
  display(inc_spins)
  display(dec_spins)
  display(dec_sections)


# Button handler function to decrease the number of sections of a spinner
def button_dec_sections(dec_sections):
  global num_sec
  num_sec -= 1 # decreases the sections by 1
  if num_sec <= 4: # minimum sections of 4
    num_sec = 4
  clear_output(wait=True) # clears the current plot
  # updates the plot with the new generated sections
  plot_data(num_sec, num_spins)
  check_error_bound() # checks if probabilities are within the variances
  # redisplays the 4 buttons
  display(inc_sections)
  display(inc_spins)
  display(dec_spins)
  display(dec_sections)


# Button handler function to decrease the number of spins of a spinner
def button_dec_spins(dec_spins):
  global num_spins
  num_spins -= 20 # decreases the spins by 20
  if num_spins <= 5: # minimum spins of 5
    num_spins = 5
  clear_output(wait=True) # clears the current plot
  # updates the plot with the new number of spins
  plot_data(num_sec, num_spins)
  check_error_bound() # checks if probabilities are within the variances
  # redisplays the 4 buttons
  display(inc_sections)
  display(inc_spins)
  display(dec_spins)
  display(dec_sections)

# calls the the functions
spinner(num_sec, num_spins) # to generate the initial spinner probabilities
plot_data(num_sec, num_spins) # plots the initial graph with the probabilities

# calls the button handlers
inc_sections.on_click(button_inc_sections)
inc_spins.on_click(button_inc_spins)
dec_sections.on_click(button_dec_sections)
dec_spins.on_click(button_dec_spins)

"""##**Analysis:**

Similar to the first graph, this block of code utilizes similar concepts of probabilities. But rather than calculating the probabilities of each section, it graphs the trends of these probabilities as the number of spins increases.

The experimental probability of the first section of the spinner is updated for every 20 spins. The theoretical probability stays constant as the number of spins does not affect the favorable outcome for the section in the spinner.

As more spins are added, graph displays a relative smaller difference between experimental probabilities and the theoretical probability showcasing the law of large numbers. This occurs as the random variations in the experimental probabilities average out with more spins. Each spin also has a smaller influence in the overall result due to more trials making it closer to the theoretical probability.

The user can alter the number of sections which changes the thoeretical probability.

## Plots a line graph to represent the trends of both experimental and theoretical probabilities of the first section in the spinner as the number of spins increases
"""

# Part 2 of the project
''' This part of the project plots the trends of both experimental and
theoretical probabilities as the number of spins increases.

  It plots a line graph to represent these probability trends of the first
  section in the spinner.

  The user can alter the number of sections (increase or decrease) showcasing
  how the theoretical probabilities differ despite being a straight line.

  '''

# function to generate the trends of the probabilities as spins increase
def prob_trends():
  global list_exprob, list_spins, list_tprob, ex_prob, t_prob
  num_spins = 0 # resets the number of spins to 0
  # stores the experimental probability of the first section in the spinner
  list_exprob = []
  list_tprob = [] # stores the constant theoretical probability
  # creates the list of spin counts through list iteration
  list_spins = [x for x in range(20, 1001, 20)]

  # to generate the probabilities for every 20 spins up to 1000 spins
  for spin in list_spins:
    num_spins = spin # sets the current number of spins
    # unpacks the probabilities from the spinner function
    t_prob, ex_prob = spinner(num_sec, num_spins)
    # appends the first section's experimental probability
    list_exprob.append(ex_prob[0])
    list_tprob.append(t_prob) # appends the theoretical probability


# function to plot the trends of the probabilities
def plot_trends():
  # plots the theoretical probability
  plt.plot(list_spins, list_tprob, label="Theoretical Probability")
  # scatter plot of experimental probability
  plt.scatter(list_spins, list_exprob)
  # line plot of experimental probability
  plt.plot(list_spins, list_exprob, label="Experimental Probability")

  # labels and title for the plot
  plt.xlabel("Number of Spins")
  plt.ylabel("Probability")
  plt.title('Experimental vs Theoretical Probability as Number of Spins Increase')
  plt.legend()
  plt.show()

# Button handler
# button to increase the sections
inc_sec_button = widgets.Button(description="Increase Sections")
display(inc_sec_button)

# button to decrease the sections
dec_sec_button = widgets.Button(description="Decrease Sections")
display(dec_sec_button)


# button handler function to increase the number of sections
def increase_sections(inc_sec_button):
  global num_sec
  num_sec += 1 # increases the number of sections by 1
  clear_output(wait=True) # clears the current graph plots
  prob_trends() # calculates both probabilities trends
  plot_trends() # plots the probabilities
  print("The current number of sections are:", num_sec)
  print("The current theoretical probability is", t_prob)
  # redisplays the 2 buttons
  display(inc_sec_button)
  display(dec_sec_button)


# button handler function to decrease the number of sections
def decrease_sections(dec_sec_button):
  global num_sec
  num_sec -= 1 # decreases the number of sections by 1
  if num_sec < 4: # minimum sections of 4
    num_sec = 4
  clear_output(wait=True) # clears the current graph plots
  prob_trends() # calculates both probability trends
  plot_trends() # plots probability trends
  print("The current number of sections are:", num_sec)
  print("The current theoretical probability is", t_prob)
  # redisplays the 2 buttons
  display(inc_sec_button)
  display(dec_sec_button)

# calls the functions
prob_trends() # calculates both probability trends
plot_trends() # plots probability trends

# calls the buttons to increase and decrease sections
inc_sec_button.on_click(increase_sections)
dec_sec_button.on_click(decrease_sections)

"""##**Analysis:**

As seen in previous graphs from above, theoretical proability majorly depends upon the number of sections that a spinner contains. This graph demonstrates two trends: the theoretical probability decreases as the total number of sections increase (up to 50 sections) and increases as the total number of sections decrease (down to 1). The concept behind this is that with more possible outcomes, the chances in choosing one section decreases indicating a decreased trend. Conversely, as the sections decrease, there are few possible outcomes increasing the likelyhood of choosing one section.

## Plots a line graph representing the trends of theoretical probabilities as the number of sections decrease and increase
"""

# Part 3 of the project
'''This part of the project plots a line graph representing the trends
of theoretical probabilities as the number of sections decrease and increase.

'''

# lists declaration
# stores increasing and decreasing section values
sequence_inc_sec = []
sequence_dec_sec = []
# stores increasing and decreasing trends of theoretical probabilities
sequence_dec_tprob = []
sequence_inc_tprob = []

# generates the trends of theoretical probability as sections increase up to 50
for i in range(1, 51):
  num_sec = i # sets the current number of sections
  sequence_inc_sec.append(num_sec) # appends the current section value
  # unpacks the probabilities from the spinner function
  t_prob, ex_prob = spinner(num_sec, num_spins)
  sequence_dec_tprob.append(t_prob) # appends each theoretical probability

# generates the trends of theoretical probability as sections decrease till 1
for i in range(50, 0, -1):
  num_sec = i # sets the current number of sections
  sequence_dec_sec.append(num_sec) # appends the current section value
  # unpacks the probabilities from the spinner function
  t_prob, ex_prob = spinner(num_sec, num_spins)
  sequence_inc_tprob.append(t_prob) # appends each theoretical probability

# to plot the generated list values for decreasing trends
plt.xlabel("Number of Sections")
plt.ylabel("Theoretical Probability")
plt.scatter(sequence_inc_sec, sequence_dec_tprob) # scatter plot
plt.plot(sequence_inc_sec, sequence_dec_tprob) # line plot
plt.title('Theoretical Probability as Sections in a Spinner Increases')
plt.show()

# to plot the generated list values for increasing trends
plt.xlabel("Number of Sections")
plt.ylabel("Theoretical Probability")
plt.gca().invert_xaxis() # inverts the x-axis for decreasing section values
plt.scatter(sequence_dec_sec, sequence_inc_tprob) # scatter plot
plt.plot(sequence_dec_sec, sequence_inc_tprob) # line plot
plt.title('Theoretical Probability as Sections in a Spinner Decreases')
plt.show()
